
NUM_INFERENCE_STEPS = 30
GUIDANCE_SCALE = 7.5

MARIO_HEIGHT = 16
MARIO_WIDTH = 16

MARIO_TILE_PIXEL_DIM = 16
MARIO_TILE_COUNT = 13

MARIO_TILESET = 'datasets\smb.json'

LR_HEIGHT = 32
LR_WIDTH = 32

LR_TILE_PIXEL_DIM = 8
LR_TILE_COUNT = 8

LR_TILESET = 'datasets\Loderunner.json'

MEGAMAN_HEIGHT = 14
MEGAMAN_WIDTH = 16

MM_TILE_PIXEL_DIM = 16
MM_SIMPLE_TILE_COUNT = 13
MM_FULL_TILE_COUNT = 39

MM_FULL_TILESET = 'datasets\MM.json'
MM_SIMPLE_TILESET = 'datasets\MM_Simple_Tileset.json'